name: Release Igor

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Pre-release'
        required: true
        default: true
        type: boolean

jobs:

  build:

    runs-on: windows-2019

    env:
      SM_CLIENT_CERT_FILE: Certificate_pkcs12.p12
      SM_HOST: ${{ secrets.SM_HOST }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.1

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Packages
      run: nuget restore source\Igor.sln

    - name: Build solution
      run: msbuild source\Igor.sln -t:rebuild -property:Configuration=Release

    - name: Code signing with Software Trust Manager
      uses: digicert/ssm-code-signing@v1.0.0

    - name: Set up certificate 
      run: | 
        echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > ${{ env.SM_CLIENT_CERT_FILE }}
        smctl credentials save ${{ secrets.SM_API_KEY }} ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
        smctl windows certsync --keypair-alias="${{ secrets.SM_KEYPAIR_ALIAS }}"
      shell: bash

    - name: Sign Executables
      run: smctl sign --fingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input bin\igorc.exe --tool signtool

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ inputs.prerelease }}
        files: bin\igorc.exe
